name: 'Build Linux package v0.1.0'

on:
  workflow_call:
    inputs:
      TAG:
        default: '_testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: '_testing'
        required: true
        type: string

jobs:
  linux:
    name: Build Linux BIN
    runs-on: ubuntu-20.04
    steps:
    - name: Update system
      run: sudo apt-get install -y libopengl0 libegl1 libxkbcommon-x11* libxcb-icccm* libxcb-image* libxcb-keysyms* libxcb-randr* libxcb-render-util* libxcb-shape* libxcb-xkb*
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    - name: Build with Pyinstaller
      run: |
        pyinstaller --clean --noconfirm .github/workflows/JWLManager.bin.spec
        mv dist/JWLManager dist/JWLManager_${{ inputs.TAG }}
    - name: Upload BIN
      uses: actions/upload-artifact@v3
      with:
        name: LinuxBIN
        path: dist/JWLManager_${{ inputs.TAG }}
