name: 'Build Packages v0.0.3'

on:
  push:
    tags:
      - '*_testing'

jobs:

  build:
    name: Build EXE
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
#              pyinstaller --clean --noconfirm .github/workflows/JWLManager.exe.spec &&
              pyinstaller --clean --noconfirm .github/workflows/JWLManager.zip.spec &&
              cd dist &&
              ren JWLManager.exe JWLManager_${{ github.ref_name }}.exe &&
              tar.exe -a -c -f JWLManager_${{ github.ref_name }}.zip JWLManager &&
#            OUT_EXE: JWLManager_${{ github.ref_name }}.exe
            OUT_ZIP: JWLManager_${{ github.ref_name }}.zip
          # - os: macos-11
          #   TARGET: macos
          #   CMD_BUILD: >
          #     pyinstaller -- clean --noconfirm JWLManager.app.spec &&
          #     cd dist/ &&
          #     zip -r9 JWLManager_${{ github.ref_name }} JWLManager.app/
          #   OUT_APP: JWLManager_${{ github.ref_name }}.app.zip
    
    # runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    # - name: Build with Pyinstaller
    #   run: | 
    #     pyinstaller --clean --noconfirm .github/workflows/JWLManager.exe.spec
    #     pyinstaller --clean --noconfirm .github/workflows/JWLManager.zip.spec
    #     cd dist
    #     ren JWLManager.exe JWLManager_${{ github.ref_name }}.exe
    #     tar.exe -a -c -f JWLManager_${{ github.ref_name }}.zip JWLManager
    - name: Build with Pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Create release
      id: gh_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: true
        prerelease: false
        body: |
          ____
          - Windows (zipped folder): JWLManager_${{ github.ref_name }}.zip
          - Windows (stand-alone): JWLManager_${{ github.ref_name }}.exe
          - macOS (zipped app): JWLManager_${{ github.ref_name }}.app.zip
        files: |
#          ./dist/${{ matrix.OUT_EXE}}
          ./dist/${{ matrix.OUT_ZIP}}
        #   ./dist/${{ matrix.OUT_APP}}
    # - name: Upload to release
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.gh_release.outputs.upload_url }}
    #     asset_path: ./dist/JWLManager_${{ github.ref_name }}.zip
    #     asset_name: JWLManager_${{ github.ref_name }}.zip
        # asset_content_type: application/vnd.microsoft.portable-executable

