name: 'Build Windows packages'

on: [ workflow_call, workflow_dispatch ]
  inputs:
    TAG: '_testing'
      required: true
      type: string

jobs:
  windows:
    name: Build Windows EXE & ZIP
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    - name: Build with Pyinstaller
      run: | 
        pyinstaller --clean --noconfirm .github/workflows/JWLManager.exe.spec
        pyinstaller --noconfirm .github/workflows/JWLManager.zip.spec
    - name: Rename & zip folder
      run: |
        cd dist
        ren JWLManager.exe JWLManager_${{ env.TAG }}.exe
        tar.exe -a -c -f JWLManager_${{ env.TAG }}.zip JWLManager
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: dist/JWLManager_${{ env.TAG }}.exe
    - name: Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        name: zip
        path: dist/JWLManager_${{ env.TAG }}.zip