name: 'Build Windows package v0.1.1'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  windows:
    name: Build Windows EXE & ZIP
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    - name: Build with Pyinstaller
      run: | 
        pyinstaller --clean --noconfirm .github/workflows/JWLManager.zip.spec
        pyinstaller --noconfirm .github/workflows/JWLManager.exe.spec
    - name: Rename & zip folder
      run: |
        cd dist
        ren JWLManager.exe JWLManager_${{ inputs.TAG }}.exe
        tar.exe -c -f JWLManager_${{ inputs.TAG }}.zip dist/JWLManager
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: WindowsEXE
        path: dist/JWLManager_${{ inputs.TAG }}.exe
    - name: Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        name: WindowsZIP
        path: dist/JWLManager_${{ inputs.TAG }}.zip